services:
  - type: web
    plan: free
    name: ai-agent-test
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/itzraiyan2580/Naruto-Uzumaki-AI-Agent-Temp/      
    branch: main
    envVars:
      - key: API_HASH 
        sync: false
      - key: APP_ID 
        sync: false
      - key: BOT_TOKEN 
        sync: false
      - key: OWNER_ID 
        sync: false
      - key: FILE_AUTO_DELETE 
        sync: false
      - key: CHANNEL_ID 
        sync: false
      - key: DB_URL 
        sync: false
      - key: DB_NAME
        sync: false
      - key: ADMINS
        sync: false
      - key: START_MESSAGE
        sync: false
      - key: FORCE_SUB_MESSAGE
        sync: false 
      - key: FORCE_SUB_CHANNEL
        sync: false
      - key: PROTECT_CONTENT
        sync: false    
    autoDeploy: false
